#
#	Makefile for dcmsign/docs
#



SHELL = /bin/sh
srcdir = .
top_srcdir = ..
configdir = ../../config

include $(configdir)/Makefile.def


all:

install:

clean:
	rm -f $(TRASH)

distclean:
	rm -f $(DISTTRASH)
