DIRSRC		=	./src/c

all: compile install

compile:	
	@make -f Makefile.centOS --no-print-directory -C $(DIRSRC) compile

install:
	@make -f Makefile.centOS --no-print-directory -C $(DIRSRC) install

clean:
	@make -f Makefile.centOS --no-print-directory -C $(DIRSRC) clean

dist:
	@make -f Makefile.centOS --no-print-directory -C $(DIRSRC) dist
	
source:
	@make -f Makefile.centOS --no-print-directory -C $(DIRSRC) source
	