/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_edu_uq_cai_TissueStack_jni_TissueStack */

#ifndef _Included_au_edu_uq_cai_TissueStack_jni_TissueStack
#define _Included_au_edu_uq_cai_TissueStack_jni_TissueStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_edu_uq_cai_TissueStack_jni_TissueStack
 * Method:    test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_au_edu_uq_cai_TissueStack_jni_TissueStack_test
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
