#
#	Makefile for dcmtls/apps
#



SHELL = /bin/sh
VPATH = ../include:../../config/include
srcdir = .
top_srcdir = ..
configdir = ../../config

include $(configdir)/Makefile.def


all: 


install:


clean:
	rm -f $(TRASH)

distclean: 
	rm -f $(DISTTRASH)


dependencies:
